version: '3.8'
services:
  headacheapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    command: ["java", "-jar", "/app.jar"]
    environment:
        - SPRING_PROFILES_ACTIVE=prod
        - JAVA_OPTS=-Xmx512m -Xms256m